openapi: 3.1.0
# ---------------------------
info:
  title: SemaDB API
  summary: No fuss vector database for AI
  description: >-
    This API provides a way to interact with a vector database, which is a type
    of database that stores data as high-dimensional vectors. Vectors are
    mathematical representations of features or attributes, and each vector has
    a certain number of dimensions, which can range from tens to thousands.

    Vector databases are used for a variety of tasks, such as similarity search,
    recommendation systems, and anomaly detection. They are particularly
    well-suited for tasks involving unstructured data, such as text, images, and
    audio.
  version: 0.1.0
  termsOfService: https://www.semafind.com/termsofservice
  contact:
    name: Semafind
    url: https://www.semafind.com/contact
    email: support@semafind.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
# ---------------------------
tags:
- name: Collection
  description: >-
    A collection is a group of points that share the same search space. For
    example, a collection could be a group of images, where each image is
    represented as a vector. The collection would be the search space for
    similarity search, and each image would be a point in that search space.
- name: Point
  description: >-
    A point is a vector with a unique identifier. It can also contain any JSON
    serialisable metadata such as an external ID, document title or image URL.
# ---------------------------
paths:
  /collections:
    summary: Endpoint for managing collections
    description: >-
      This endpoint covers operations for collections as a whole, such as
      creating a new collection or listing all collections.
    post:
      tags:
        - Collection
      summary: Create a new collection
      description: >-
        Creates a new collection if it does not already exist. The maximum
        number of collections per user is restricted based on the plan. Before
        you can insert and search points, you must create a collection.
      operationId: CreateCollection
      requestBody:
        description: The collection to create
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  $ref: '#/components/schemas/CollectionId'
                vectorSize:
                  $ref: '#/components/schemas/VectorSize'
                distanceMetric:
                  $ref: '#/components/schemas/DistanceMetric'
            examples:
              SampleCreateCollection:
                summary: Sample create collection
                description: A sample collection to create with id mycollection, vector size 2 and euclidean distance.
                value:
                  id: mycollection
                  vectorSize: 2
                  distanceMetric: euclidean
      responses:
        '200':
          $ref: '#/components/responses/SuccessfulMessageResponse'
          description: The collection was created
        '403':
          $ref: '#/components/responses/ErrorMessageResponse'
          description: The maximum collecton quota may be reached
        '409':
          $ref: '#/components/responses/ErrorMessageResponse'
          description: The collection already exists
    get:
      tags:
        - Collection
      summary: List user collections
      description: >-
        Returns a list of all collections for the current user. The list is not
        sorted by any value and the order may change between requests.
      operationId: ListCollection
      responses:
        '200':
          description: The list of collections
          content:
            application/json:
              schema:
                type: object
                properties:
                  collections:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          $ref: '#/components/schemas/CollectionId'
                        vectorSize:
                          $ref: '#/components/schemas/VectorSize'
                        distanceMetric:
                          $ref: '#/components/schemas/DistanceMetric'
              examples:
                SampleCollectionList:
                  summary: Sample collection list
                  description: A sample collection list with one collection
                  value:
                    collections:
                      - id: mycollection
                        vectorSize: 2
                        distanceMetric: euclidean
# ---------------------------
  /collections/{collectionId}:
    summary: Endpoint for managing a specific collection
    description: >-
      These endpoints interact with a single collection. The collection must
      exist before you can use these endpoints.
    parameters:
      - $ref: '#/components/parameters/CollectionId'
    get:
      tags:
        - Collection
      summary: Get the details of a collection
      description: >-
        This endpoint attempts to also list the shards currently available in
        the collection. Some shards may be temporarily unavailable. In that
        case, you can retry at a future time.
      operationId: GetCollection
      responses:
        '200':
          description: Collection with available shard details
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    $ref: '#/components/schemas/CollectionId'
                  vectorSize:
                    $ref: '#/components/schemas/VectorSize'
                  distanceMetric:
                    $ref: '#/components/schemas/DistanceMetric'
                  shards:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                        pointCount:
                          type: integer
              examples:
                SampleCollection:
                  summary: Sample collection
                  description: A sample collection with shard information
                  value:
                    id: mycollection
                    vectorSize: 2
                    distanceMetric: euclidean
                    shards:
                      - id: fff3a226-b9f8-4375-8dbd-1a240e000705
                        pointCount: 1000
        '503':
          $ref: '#/components/responses/ErrorMessageResponse'
          description: Some downstream components may be temporarily unavailable
    delete:
      tags:
        - Collection
      summary: Delete a collection
      description: >-
        Deletes a collection and all of its points. This operation is
        irreversible. If you want to delete only some points, use the bulk
        delete endpoint. If some shards are temporarily unavailable, the
        operation will still succeed, but some of the data will be deleted in
        the future.
      operationId: DeleteCollection
      responses:
        '200':
          $ref: '#/components/responses/SuccessfulMessageResponse'
          description: The collection and all of its data was deleted
        '202':
          $ref: '#/components/responses/SuccessfulMessageResponse'
          description: The collection was deleted, but some of the data will be deleted in the future
# ---------------------------
  /collections/{collectionId}/points:
    summary: Endpoint for bulk managing points in a collection
    description: >-
      The bulk points endpoint is more efficient and operates on multiple points
      at once. It is recommended to use this endpoint for inserting, updating
      and deleting points.
    parameters:
      - $ref: '#/components/parameters/CollectionId'
    post:
      tags:
        - Point
      summary: Insert new points into the collection
      description: >-
        This endpoint assumes all points to be inserted are new points and does
        not check for duplication. It is important to ensure consistency of the
        database you do not insert duplicate points. If you are unsure if a
        point exists, you can leave the id field blank and the database will
        assign a new id. *For cosine distance, you must normalise the vectors
        prior to inserting them.*
      operationId: InsertPoint
      requestBody: 
        description: Points to insert
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - points
              properties:
                points:
                  type: array
                  minItems: 1
                  maxItems: 10000
                  items:
                    type: object
                    required: 
                      - vector
                    properties:
                      id:
                        type: string
                        format: uuid
                      vector:
                        $ref: '#/components/schemas/Vector'
                      metadata:
                        $ref: '#/components/schemas/PointMetadata'
            examples:
              SampleInsertPoints:
                summary: Sample insert points
                description: A sample list of points to insert
                value:
                  points:
                    - vector: [4.2, 2.4]
                    - vector: [1.2, 3.4]
                      metadata:
                        externalId: 42
                    - id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
                      vector: [3.4, 2.4]
                      metadata:
                        externalId: 43
      responses:
        '200':
          description: >-
            The operation was successful but you must check the failedRanges to
            ensure all the points were inserted. If some points were not
            inserted, you can retry the operation by using the failedRanges
            depending on the error. For example, if the failedRanges is [[0,
            2]], you can retry the operation by sending the first two points
            again.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    examples:
                      - partial success
                  failedRanges:
                    type: array
                    description: >-
                      A list of ranges of points that failed to insert. Each
                      range has a start and an end index.  The end index is
                      exclusive. For example, if the range is [0, 2], the first
                      two points failed to insert.
                    items:
                      type: object
                      properties:
                        shardId:
                          type: string
                          format: uuid
                        start:
                          type: integer
                        end:
                          type: integer
                        error:
                          type: string
              examples:
                SuccessfulInsertPointsResponse:
                  summary: Fully successful insert points response
                  description: A sample response indicating full success
                  value:
                    message: success
                    failedRanges: []
                SamplePartialInsertPointsResponse:
                  summary: Partial success insert points response
                  description: A sample response indicating partial success
                  value:
                    message: partial success
                    failedRanges:
                      - shardId: fff3a226-b9f8-4375-8dbd-1a240e000705
                        start: 0
                        end: 2
                        error: point already exists
        '403':
          $ref: '#/components/responses/ErrorMessageResponse'
          description: Maximum point quota per collection may be reached
        '503':
          $ref: '#/components/responses/ErrorMessageResponse'
          description: Some downstream components may be temporarily unavailable
    put:
      tags:
        - Point
      summary: Update existing points with new data
      description: >-
        This endpoint allows updating point vectors and metadata. It does not
        allow updating the point id. If you want to update the id, you must
        delete the point and insert a new point. The points are required to
        exist before you can update them. You can check the failedIds to see
        which points failed to update.
      operationId: UpdatePoint
      requestBody:
        description: Points to update
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - points
              properties:
                points:
                  type: array
                  minItems: 1
                  maxItems: 100
                  items:
                    type: object
                    required:
                      - id
                      - vector
                    properties:
                      id:
                        type: string
                        format: uuid
                      vector:
                        $ref: '#/components/schemas/Vector'
                      metadata:
                        $ref: '#/components/schemas/PointMetadata'
            examples:
              SampleUpdatePoints:
                summary: Sample update points
                description: A sample list of points to update
                value:
                  points:
                    - id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
                      vector: [4.2, 2.4]
                    - id: 3fa85f64-5717-4562-b3fc-2c963f66afa7
                      vector: [1.2, 3.4]
                      metadata:
                        externalId: 42
      responses:
        '200':
          description: Updated points
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    examples:
                      - partial success
                  failedIds:
                    type: array
                    items:
                      type: string
                      format: uuid
              examples:
                SuccessfulUpdatePointsResponse:
                  summary: Successful update points response
                  description: A sample response indicating full success
                  value:
                    message: success
                    failedIds: []
                SamplePartialUpdatePointsResponse:
                  summary: Partial update points response
                  description: A sample response indicating partial success
                  value:
                    message: partial success
                    failedIds:
                      - 3fa85f64-5717-4562-b3fc-2c963f66afa6
    delete:
      tags:
        - Point
      summary: Delete points by id
      description: >-
        Bulk delete points based on id. This endpoint does not check if the
        points exist. If you attempt to delete a point that does not exist, it
        will be ignored and included in the failedIds list.
      operationId: DeletePoint
      requestBody:
        description: Point IDs to delete
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - ids
              properties:
                ids:
                  type: array
                  minItems: 1
                  maxItems: 100
                  items:
                    type: string
                    format: uuid
            examples:
              SampleDeletePoints:
                summary: Sample delete points
                description: A sample list of point ids to delete
                value:
                  ids:
                    - 3fa85f64-5717-4562-b3fc-2c963f66afa6
                    - 3fa85f64-5717-4562-b3fc-2c963f66afa7
      responses:
        '200':
          description: Deleted points
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    examples:
                      - partial success
                  failedIds:
                    type: array
                    items:
                      type: string
                      format: uuid
              examples:
                SuccessfulDeletePointsResponse:
                  summary: Successful delete points response
                  description: A sample response indicating full success
                  value:
                    message: success
                    failedIds: []
                SamplePartialDeletePointsResponse:
                  summary: Partial delete points response
                  description: A sample response indicating partial success
                  value:
                    message: partial success
                    failedIds:
                      - 3fa85f64-5717-4562-b3fc-2c963f66afa6
# ---------------------------
  /collections/{collectionId}/points/search:
    summary: Search points
    description: >-
      This endpoint allows searching for points in a collection.
    parameters:
      - $ref: '#/components/parameters/CollectionId'
    post:
      tags:
        - Point
      summary: Vector search
      description: >-
        Perform similarity search on points in a collection. The search is
        performed using a vector, which is a mathematical representation of the
        point. The vector must have the same number of dimensions as the vectors
        in the collection. The search returns the most similar points to the
        vector, along with the distance between the vector and the points.
      operationId: SearchPoint
      requestBody:
        description: Vector to similarity search
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - vector
              properties:
                vector:
                  $ref: '#/components/schemas/Vector'
                limit:
                  type: number
                  description: Maximum number of points to search
                  minimum: 1
                  maximum: 75
                  default: 10
            examples:
              SampleSearchPoint:
                summary: Sample search point
                description: A sample vector to search with default limit
                value:
                  vector: [4.2, 2.4]
              SampleSearchPointWithLimit:
                summary: Sample search point with limit
                description: A sample vector to search with limit 10
                value:
                  vector: [4.2, 2.4]
                  limit: 10
      responses:
        '200':
          description: Point search results sorted by distance
          content:
            application/json:
              schema:
                type: object
                properties:
                  points:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                        distance:
                          type: number
                          description: Distance between the vector and the point
                          examples:
                            - 4.2
                        metadata:
                          $ref: '#/components/schemas/PointMetadata'
              examples:
                SampleSearchPointResponse:
                  summary: Sample search point response
                  description: A sample response with two points
                  value:
                    points:
                      - id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
                        distance: 4.2
                        metadata:
                          externalId: 42
                      - id: 3fa85f64-5717-4562-b3fc-2c963f66afa7
                        distance: 4.3
                        metadata: null
# ---------------------------
components:
  parameters:
    CollectionId:
      name: collectionId
      in: path
      description: The unique identifier of the collection
      required: true
      schema:
        $ref: '#/components/schemas/CollectionId'
  schemas:
    CollectionId:
      type: string
      title: Collection Id
      description: The unique identifier of the collection
      pattern: "^[a-z0-9]{3,16}$"
      examples:
        - mycollection
        - abc
    VectorSize:
      type: number
      description: The size of the vectors in the collection
      minimum: 1
      maximum: 2000
      examples:
        - 2
    DistanceMetric:
      type: string
      enum:
        - euclidean
        - cosine
    Vector:
      type: array
      description: Point vector, aka embedding
      minItems: 1
      maxItems: 2000
      items:
        type: number
      examples:
        - [4.2, 2.4]
    PointMetadata:
      type: object
      description: JSON serialisable point metadata
      examples:
        - externalId: 42
  responses:
    SuccessfulMessageResponse:
      description: Operation was successful
      content:
        application/json:
          schema:
            type: object
            required:
              - message
            properties:
              message:
                type: string
                description: A message indicating the result of the operation
            examples:
              - message: Operation successful
          examples:
            Success:
              summary: A successful response
              description: The operation was successful
              value:
                message: success
    ErrorMessageResponse:
      description: Something unexpected happened
      content:
        application/json:
          schema:
            type: object
            required:
              - error
            properties:
              error:
                type: string
                description: An error message hopefully describing the problem
          examples:
            GeneralError:
              summary: General error
              description: Something unexpected happened
              value:
                error: Something went wrong